name: fl_paging
description: A new Flutter package support paginating for Listview, Gridview and NestedScrollView
version: 2.1.1
homepage: https://github.com/dangngocduc/flutter_paging
repository: https://github.com/dangngocduc/flutter_paging
issue_tracker: https://github.com/dangngocduc/flutter_paging/issues
documentation: https://github.com/dangngocduc/flutter_paging

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  tuple: ^2.0.0
  async: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
flutter:
